services:
  check-mate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}
      - LOCATION=${LOCATION:-Unknown}
      - HEALTHCHECKURL=${HEALTHCHECKURL:-}
    restart: unless-stopped